controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /AncaAdrian
    controller: App\Controller\index

Qumseya-Ibrahim:
    path: /qumseya-Ibrahim
    controller: App\Controller\QumseyaIbrahimController::number

Mihai_Baciu:
    path: /MihaiBaciu
    controller: App\Controller\MihaiBaciuController::PersonalPage

Precup-Cristian:
    path: /PrecupCristian
    controller: App\Controller\PrecupCristianController::number

Puia-Daniela:
    path: /PuiaDaniela
    controller: App\Controller\PuiaDanielaController::number

<<<<<<< HEAD
MunteanAlin:
    path: /MunteanAlin
    controller: App\Controller\MunteanAlinController::number
=======
MirceaRaul:
    path: /MirceaRaul
    controller: App\Controller\MirceaRaulController::number
    
Capilnas-Matei:
    path: /CapilnasMatei
    controller: App\Controller\CapilnasMateiController::number
>>>>>>> bb0e72734f1b07862c13fb3f3c55c957d16f34bc
