controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
<<<<<<< HEAD
show:
    path: /AncaAdrian
    controller: App\Controller\show
=======
index:
    path: /AncaAdrian
    controller: App\Controller\index
>>>>>>> 097b9b46d4b34eb14d0f2e86c788c8211bf18647
