controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /AncaAdrian
    controller: App\Controller\index

Qumseya-Ibrahim:
    path: /qumseya-Ibrahim
    controller: App\Controller\QumseyaIbrahimController::number

Precup-Cristian:
    path: /PrecupCristian
    controller: App\Controller\PrecupCristianController::number

MunteanAlin:
    path: /MunteanAlin
    controller: App\Controller\MunteanAlinController::number
