controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /AncaAdrian
    controller: App\Controller\index

Qumseya-Ibrahim:
    path: /qumseya-Ibrahim
    controller: App\Controller\QumseyaIbrahimController::number

<<<<<<< HEAD
Mihai_Baciu:
    path: /MihaiBaciu
    controller: App\Controller\MihaiBaciuController::PersonalPage
=======
Precup-Cristian:
    path: /PrecupCristian
    controller: App\Controller\PrecupCristianController::number

Puia-Daniela:
    path: /PuiaDaniela
    controller: App\Controller\PuiaDanielaController::number
>>>>>>> 4c2a0a0f02c906c82a4979a6d503f7503e5320fd
